server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///class_database
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: stu_service_classes
  registry:
    address: zookeeper://192.168.75.99:2181
  protocol:

    port: -1
