server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql:///stu_database
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: stu_service_student
  registry:
    address: zookeeper://192.168.75.99:2181
  protocol:
    port: -1
  consumer:
    check: false